### ISSUE TITLE
Any way to run code coverage via command line?

### ISSUE THREAD

**Issue by achan** [sglanzer/ember-cli-blanket#13]
I'm new to ember-cli and Ember in general, but is there a way to run blanket from command line? Any options to enable it via `ember test`? Moreover, is there an easy way to generate lcov reports to feed in to services like coveralls / code climate?

**Comment by kiwiupover** [comment]
thanks @achan for looking into command line interface I would totally use it. cheers

**Comment by sglanzer** [comment]
We're going to start looking into the headless run as well as LCOV reports that can be fed into systems like Sonar or TeamCity.  @achan Have you made any progress looking into this that we could build on?

**Comment by achan** [comment]
Nope sorry, not able to work on this at the moment..

**Comment by sglanzer** [comment]
@achan No problem, just wanted to make sure we didn't duplicate effort.

**Comment by kiwiupover** [comment]
@achan Let me know if I can help with the headless coverage reports either testing or coding.

**Comment by achan** [comment]
@kiwiupover I'm pretty much not involved with this issue other than creating it.. I believe @sglanzer is your guy :)

**Comment by kiwiupover** [comment]
Ok I get it.

**Comment by grese** [comment]
@sglanzer - I would like to get involved.. Our team really needs headless tests, and custom coverage reporting.  I have some spare time to spend on this because it is the only item keeping our team from onboarding to ember-cli :)

Could you please point me to the necessary hooks as you mentioned above?  I would love these features :)

**Comment by sglanzer** [comment]
@grese Excellent, getting this feature would be great.

https://github.com/alex-seville/blanket/tree/master/test/custom-reporter is the basic blanketjs example for custom reporters.

This appears to be reasonable example for running with phantomjs and a custom reporter: https://github.com/ModelN/grunt-blanket-qunit 

That uses grunt but I would imagine that it could also be driven using testem (standard ember-cli).


The current implementation takes the result of the ES6 to ES5 conversion performed in the ember-cli build, loops over the entries store in the requirejs.entries list, instruments each entry using blanket, loads all of the entries and then lets qunit start the test run (there is a flag set to block the run until the entries have been loaded).

The mocha case is a bit different, @mheisig did the work for mocha, so if you want to go that route he would be able to give you more information.


I know this isn't a lot to go on, but let me know if I can do anything else to help.

**Comment by sglanzer** [comment]
Another note - I'm not a fan of how the project hooks into ember-cli currently, it was a hack effort and I think modifying the instrumentation to run during the postProcess hook http://hashrocket.com/blog/posts/a-compendium-of-hooks-in-embercli#postprocess would be a better idea.

If you can get the headless runner going with the current implementation, cool - otherwise we may need a bit better control over the execution and I think that hook might be the right way to get better control.

**Comment by grese** [comment]
I've managed to get the lcov file working when the user hits localhost:4200?coverage=true (with both mocha and qunit), but still need to get it working in the headless runner...(that's where the bulk of the work will be, I suppose.).

Thanks for the pointers :)
I'll also look into the hooks while I'm at it because I think your're correct - (we will probably need more control to make this work in headless runners).

**Comment by max-winderbaum** [comment]
@grese, could you publish your work thusfar? I'd love to see it :+1:

**Comment by DebVortex** [comment]
It has been a couple of days, since @grese posted that he working on a approach of tackling headless coverage.

Does anyone have new information about that? I'm really interested in this topic as well.

**Comment by jschilli** [comment]
I dug into this a few days ago while looking @ the overall coverage updates

Stating the obvious we need to:
[] generate an lcov report from blanket
[] get the lcov report written to the filesystem

I'm working on a POC using an ember test middleware to take the results when the the blanket test ends.

setting up the lcov reporter is a bit of PITA but I'm close - will advise
