### ISSUE TITLE
Broccoli TreeMerger fails

### ISSUE THREAD

**Issue by dfalling** [sglanzer/ember-cli-blanket#165]
I'm getting this failure after installing ember-cli-blanket.  I've cleaned out my package folders and tmp directory, and still get this.  Any ideas?

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor)] failed with:
Error: ENOENT: no such file or directory, scandir '.../tmp/broccoli_merge_trees-input_base_path-6lDy8xJV.tmp/2/'
    at Object.fs.readdirSync (fs.js:913:18)
    at .../node_modules/broccoli-merge-trees/index.js:200:17
    at Array.map (native)
    at BroccoliMergeTrees._mergeRelativePath (.../node_modules/broccoli-merge-trees/index.js:198:26)
    at BroccoliMergeTrees.build (.../node_modules/broccoli-merge-trees/index.js:83:24)
    at .../node_modules/broccoli-plugin/read_compat.js:93:34
```

**Comment by sglanzer** [comment]
@dfalling The version of ember-cli probably makes a difference here, but I haven't seen that issue.  In general I'm recommending that people try to use https://github.com/kategengler/ember-cli-code-coverage these days since we/I don't really have time to maintain this project and most of the community effort (including mine) is going into the new project.

**Comment by dfalling** [comment]
Thanks @sglanzer, I totally missed the shift to ember-cli-code-coverage.  Are you open to a PR that updates the README to recommend this?  Thanks!

**Comment by sglanzer** [comment]
@dfalling yeah, absolutely 👍
