### ISSUE TITLE
Ability to disable coverage reporting?

### ISSUE THREAD

**Issue by jschilli** [sglanzer/ember-cli-blanket#26]
Before I put up a PR for this I'd love some guidance/feedback on best way to accomplish this.

I'd like to be able to disable coverage reporting for a given run of tests.  I have a totally hacked version that uses a query string `?coverage=1` and then wraps the blanket loader with a conditional.

The use case is that when debugging tests in the browser I'd prefer stepping through un-annotated code.

It might be preferable to preserve existing behavior (on by default) and just expose a variable that can be controlled by the user - then the triggering mechanism could be a query string or other mechanism

thoughts?

**Comment by sglanzer** [comment]
It's funny, because most of the project consists of these sorts of hacks =)

I've had a few people ask for this at my work and I agree, we should only be instrumenting the code when coverage is requested (e.g. the enable coverage checkbox is on).

I went searching for the hooks for those checkboxes before in the ember-cli code, but it's a minefield and I didn't have much luck.  If you have something that works, even if it's a hack, I'm happy with that.

I'll have to engage people closer to the ember-cli core at some point to provide official hooks for this project so that it's not so hacky, but in the meantime hack away!

**Comment by sglanzer** [comment]
Is the query string something you have to manually add to the URL, or is there a way we can trigger it from the current Enable Coverage checkbox?  Triggering from the checkbox would be really nice.

**Comment by jschilli** [comment]
I'm running mocha here - so no Enable Coverage checkbox - if I wrap the bits in a conditional we can do anything - although I suspect that enable coverage would trigger a reload with a query param 

Let me cleanup my hack and play with a few options - will be later today/tomorrow before I have a PR

thx

**Comment by sglanzer** [comment]
So for Qunit there is the ability to add config, which is how blanket adds the checkbox:

QUnit.config.urlConfig.push({
id: "coverage",
label: "Enable coverage",
tooltip: "Enable code coverage."
});

When checked, this puts a query param on the URL 'tests?coverage'

It's possible Mocha has the same kind of config - I'll do a little digging.
