### ISSUE TITLE
lcov.dat incompatible with codeclimate-test-reporter

### ISSUE THREAD

**Issue by givanse** [sglanzer/ember-cli-blanket#63]
...TOKEN=... codeclimate < lcov.dat

fails with:

    ENOENT, no such file or directory

Its a matter of just moving up one level in the folders hierarchy and it will find the directory.

    ...TOKEN=... codeclimate < app-folder/lcov.dat

Also, all the entries in `lcov.dat` reference folders only and it results in:

    EISDIR, illegal operation on a directory

So, codeclimate is expecting an entry for each file, a full path.

Am I missing an option for this? Or this is a feature that needs to be added?

**Comment by jrjohnson** [comment]
I'm having this problem as well and I'm not sure where to start debugging.  I can't seem to find a file standard reference for lcov to see what this is supposed to look like.  Seems to be obscured on google by a linux utility for visualizing gcov data.  Anyone have a pointer to how lcov is supposed to work?

**Comment by jschilli** [comment]
There are lots of caveats around lcov coverage as discussed here: https://github.com/sglanzer/ember-cli-blanket/pull/38#issuecomment-88476342 <https://github.com/sglanzer/ember-cli-blanket/pull/38#issuecomment-88476342> and in the release notes.

I’m not sure what code-climate is needing.  Somewhere in that thread there is a ref to lcov file format.

In short, the lcov reporting is on AMD modules which may or may not have a direct relationship to files on the file system.

I hope to explore other options to generate coverage data but the tradeoffs in all currently available choices are suboptimal.

**Comment by jrjohnson** [comment]
Ah -Thanks, I was i the right place, just had to actually read.  The format for the file is described here: http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php under the FILES heading.

I completely understand that the transpile process for ES6 + any babeljs changes is going to make this hard to use effectively, however I think that even the data as is will provide me with coverage metrics that can point to problems with a pull request.  I will dig into the output and see what code climate is expecting to figure out where work need to be done.

**Comment by jrjohnson** [comment]
I think this issue exists in two parts:

1) Codeclimate parses the lcov file for path entries to files.  Some files do not exist in the source, they come from addons during the broccoli build.  [for example: todomvc-ember-cli/initializers/app-version from the fixture test file](https://github.com/sglanzer/ember-cli-blanket/blob/master/tests/fixtures/lcov.dat#L23) I put in a [PR with code igniter](https://github.com/codeclimate/javascript-test-reporter/pull/20) to skip these files instead of dying with the error @givanse reported ```ENOENT, no such file or directory``` 

2) The lcov output does not contain real file paths.  [for example router](https://github.com/sglanzer/ember-cli-blanket/blob/master/tests/fixtures/lcov.dat#L45) should be ```app/router.js```.  I hesitate to put in a PR here because I'm not sure if this behavior is what is expected from some reason.  I'm able to submit code coverage data successfully to code igniter by replacing ```SF:APP_NAME/router``` with ```app/router.js``` in the lcov.dat file.  This accounts for every file in my test output other than ```config/environment.js``` which I don't really need to test.  This is a pretty easy grep replace if you don't want to change the reporter.

**Comment by jschilli** [comment]
I think a reasonable option would be to have a renamer option in the `lcovOptions`. It could be a Boolean that defaults to false or a function that given a module reference returns the name to output. 

I would suggest that default behavior remains as is. 

I'm in the air ATM but there is an ember-cli issue that goes to normalizing module references to match the file system. I'll need to dig that up and tie it to this issue. 

As you point out the model breaks with addon contributed content. 

-jeff

**Comment by jrjohnson** [comment]
Seems like a good set of options to me.  A function that can process the name would work well.  
I spent some time looking at the [ember-resolver](https://github.com/ember-cli/ember-resolver) and I don't see a way to go from a resolved module name back to a file system path.  Once you have your feet on the ground let me know if you have a link to somewhere that does this already, or if its something that needs to get added. 

I will take a stab at a PR to add the renamer option.  Should that go in lcovOptions or in cliOptions?  Seems like it would belong in cliOptions as it might be equally useful in other reporters.  Thoughts?

**Comment by jschilli** [comment]
@jrjohnson you didn't see my hand waving vigorously in the air while describing the mythical renamer function :-)  It doesn't exist as a single entity b/c the ember-resolver manufactures the output module name.  In the case you mentioned above if the renamer is passed `APP_NAME/router` you would return `app/router.js`.  

WRT to being in lcovOptions vs cliOptions I would suggest lcovOptions to start.  My concern with the renamer in general is that even with warnings in the README that coverage line information doesn't match files on the file system folks will look at the output and expect otherwise.

I would mark the renamer option in the README as `experimental` 

One other thought (one which I'll open up as a separate issue) is that if we were to attack the issue by going back to blanket.js and look at the line annotation function with an eye towards preserving correspondence to the input file the renamer function would become useful as would the line data.

**Comment by elwayman02** [comment]
Does anyone have any thoughts on the lcov report including tests for the addons, which ends up with files that don't "exist" in the repo where they are supposed to?  This is still a blocker to being able to use codeclimate.

P.S. The suggested renamer method doesn't quite work, because my lcov report included config/environment.js, which does not live under the app/ directory.  I had to do something like this:

```
            renamer: function (moduleName) {
                var expression = /^APP_NAME/;
                var name = moduleName.replace(/^APP_NAME\/config/, 'config');
                return name.replace(expression, 'app') + '.js';
            }
```

**Comment by jrjohnson** [comment]
I put in a PR to codeclimate to ignore the lines for files that don't exist.  If you need this behavior maybe a comment on https://github.com/codeclimate/javascript-test-reporter/pull/20 will speed things up.

You're correct that if you want to parse the config file as part of the tested paths you would want to change it as well, I didn't want the README option to be too complicated and figured that was a file that could be safely ignored in most cases.

**Comment by amokan** [comment]
not a great workaround, but i run a quick ruby shell script post build in my CI process to fix the formatting for code-climate. Been working well for weeks now. But a fix to `ember-cli-blanket` would obviously be nice.

Either way, if someone wants the ruby script I'm using - you can find it here: https://gist.github.com/amokan/a30afe721ea225a34437

**Comment by elwayman02** [comment]
@amokan the master branch has a new feature (see the README) that does this for you as part of ember-cli-blanket.

**Comment by amokan** [comment]
@elwayman02 thanks man. Will check it out.

**Comment by ryanlabouve** [comment]
On my CI server I had to install the reporter from github `npm install -g git+https://github.com/codeclimate/javascript-test-reporter.git`... guess this will be resolved once they do a new release to NPM?

My coverage is reporting now though! Thanks @jrjohnson for that PR to codeclimate!

**Comment by jrjohnson** [comment]
Yes, the PR is merged and they promised me a release on twitter last week.  I will bug them again in a few days.  You can actually add the github directly into your package.json like:
```"codeclimate-test-reporter": "codeclimate/javascript-test-reporter#master"```

If you want access to this before  a release.

**Comment by ryanlabouve** [comment]
:+1: Thanks! Will do.

**Comment by sglanzer** [comment]
@jrjohnson Every time I see your name pop up in my email I think of this https://www.youtube.com/watch?v=6hRXxnTue5w =)

Anyhow, when code climate publishes can someone respond here so we can close this off (I'm assuming there isn't any outstanding work to be done against ember-cli-blanket for this)?

**Comment by jrjohnson** [comment]
Nice.  I'm going to use that for my walkup music!  

Code climate published 0.1.0 which has this fix.  I'm having some trouble verifying if it works because of a sporadic problem generating the lcov file I'm having in my app.  Since thats taking a long time to track down maybe someone else can validate?  Otherwise I think this is probably working and can be closed.

**Comment by jrjohnson** [comment]
@sglanzer I can confirm that I'm now generating lcov data and passing it to code climate for consumption with the released versions of code-climate-test-reporter and ember-cli-blanket.  This can be closed.

**Comment by givanse** [comment]
Thank you :clap: :fireworks:
